# Generated by Django 3.2.4 on 2021-06-24 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hssapis', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Announcements',
            new_name='Announcement',
        ),
        migrations.RenameModel(
            old_name='Awards',
            new_name='Award',
        ),
        migrations.RenameModel(
            old_name='Projects',
            new_name='Project',
        ),
        migrations.RenameModel(
            old_name='Students',
            new_name='Student',
        ),
    ]
