# Generated by Django 3.2.4 on 2021-06-24 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hssapis', '0004_alter_committeeperson_committee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conf_work_pres',
            name='type',
            field=models.CharField(choices=[('Conference', 'Conference'), ('Workshop', 'Workshop'), ('Presentation', 'Presentation')], default='Conference', max_length=20),
        ),
    ]
