# Generated by Django 3.2.4 on 2021-06-24 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hssapis', '0005_alter_conf_work_pres_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
