# Generated by Django 3.2.4 on 2021-06-28 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hssapis', '0008_auto_20210624_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='interests',
            field=models.TextField(blank=True, null=True),
        ),
    ]
