# Generated by Django 3.2.4 on 2021-06-29 11:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hssapis', '0009_alter_faculty_interests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='past_talk',
            name='date',
            field=models.DateField(default=datetime.date(2021, 6, 29)),
        ),
    ]
