# Generated by Django 3.2.4 on 2021-06-29 11:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hssapis', '0010_alter_past_talk_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='past_talk',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 6, 29, 11, 16, 59, 238492, tzinfo=utc)),
        ),
    ]
