# Generated by Django 3.2.4 on 2021-06-29 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hssapis', '0015_alter_past_talk_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='date',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='conf_work_pres',
            name='date',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='past_talk',
            name='date',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='special_talk',
            name='date',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
