# Generated by Django 3.2.4 on 2021-06-29 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hssapis', '0016_auto_20210629_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='date',
            field=models.FileField(blank=True, null=True, upload_to='announcements/'),
        ),
    ]
