# Generated by Django 3.2.4 on 2021-06-29 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hssapis', '0017_alter_announcement_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to='announcements/'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='date',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
